# -*- coding: utf-8 -*-
"""Body_Mass_Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wVmfKJ1KTmFobStmBfeeXingZ4EsFZ8
"""

def calculate_bmi(weight, feet, inches):
    total_inches = feet * 12 + inches
    bmi = (weight / (total_inches ** 2)) * 703
    return round(bmi, 1)

def get_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi <= 24.9:
        return "Normal weight"
    elif bmi <= 29.9:
        return "Overweight"
    else:
        return "Obese"

import unittest

class TestBMI(unittest.TestCase):

    def test_bmi_value(self):
        self.assertEqual(calculate_bmi(150, 5, 6), 24.2)

    def test_categories(self):
        self.assertEqual(get_category(18.4), "Underweight")
        self.assertEqual(get_category(18.5), "Normal weight")
        self.assertEqual(get_category(25.0), "Overweight")
        self.assertEqual(get_category(30.0), "Obese")

unittest.main(argv=[''], exit=False)

feet = int(input("Feet: "))
inches = int(input("Inches: "))
weight = float(input("Weight (lbs): "))

bmi = calculate_bmi(weight, feet, inches)
category = get_category(bmi)

print("BMI:", bmi)
print("Category:", category)